### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by egormoroz** [dallinson/Chessatron#75]
Hi!

Great progress with your engine! However, could you please provide binaries for Windows (and optionally Linux) so that anyone could try out your engine easily. This is especially true for people who don't have CMake or C++ 20 compatible compiler configured on their system.

**Comment by dallinson** [comment]
Hi-I realise I've managed to ignore this for about three months!  I'm going to close this for now; binaries are definitely planned but they're waiting for the next release-which will come when I can squeeze some more elo out of the engine.

**Comment by egormoroz** [comment]
badass dude
